### ISSUE TITLE
Histogram: adding a variable label crashes on register

### ISSUE THREAD

**Issue by steveeJ** [tikv/rust-prometheus#306]
[This example](https://github.com/steveeJ/hello_rust/blob/b4530ae93a40092e3b6e1c11ee16319fb2745176/prometheus-histogram-value/src/main.rs) leads to the following crash at runtime:

```console
$ RUST_BACKTRACE=full cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.02s
     Running `target/debug/prometheus-histogram-value`
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', /home/steveej/.cargo/git/checkouts/rust-prometheus-0afd92d0f40cf12e/d919ccd/src/value.rs:139:30
stack backtrace:
   0:     0x5573bbeaf3d4 - backtrace::backtrace::libunwind::trace::heb43798aede8bd30
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1:     0x5573bbeaf3d4 - backtrace::backtrace::trace_unsynchronized::had2ba7dec4bd2732
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2:     0x5573bbeaf3d4 - std::sys_common::backtrace::_print_fmt::hda61f46e822731b2
                               at src/libstd/sys_common/backtrace.rs:84
   3:     0x5573bbeaf3d4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hfe37fa5de6572965
                               at src/libstd/sys_common/backtrace.rs:61
   4:     0x5573bbecd4ac - core::fmt::write::h74887d18db27282c
                               at src/libcore/fmt/mod.rs:1025
   5:     0x5573bbead8c7 - std::io::Write::write_fmt::h6808f3d5eceed5e5
                               at src/libstd/io/mod.rs:1426
   6:     0x5573bbeb13be - std::sys_common::backtrace::_print::hcc0fd4b3552039ef
                               at src/libstd/sys_common/backtrace.rs:65
   7:     0x5573bbeb13be - std::sys_common::backtrace::print::h1c9c5c1c0505592d
                               at src/libstd/sys_common/backtrace.rs:50
   8:     0x5573bbeb13be - std::panicking::default_hook::{{closure}}::hefb6085c1ab83a59
                               at src/libstd/panicking.rs:193
   9:     0x5573bbeb10b1 - std::panicking::default_hook::h1b037d2bf0657ab3
                               at src/libstd/panicking.rs:210
  10:     0x5573bbeb19eb - std::panicking::rust_panic_with_hook::h787d7f532b084b9a
                               at src/libstd/panicking.rs:471
  11:     0x5573bbeb159e - rust_begin_unwind
                               at src/libstd/panicking.rs:375
  12:     0x5573bbec9b4e - core::panicking::panic_fmt::h76b979c035808e69
                               at src/libcore/panicking.rs:84
  13:     0x5573bbec9b15 - core::panicking::panic_bounds_check::hdf3f3ae37b439756
                               at src/libcore/panicking.rs:62
  14:     0x5573bbce4b5d - prometheus::value::make_label_pairs::h45ec435badfeddc9
                               at /home/steveej/.cargo/git/checkouts/rust-prometheus-0afd92d0f40cf12e/d919ccd/src/value.rs:139
  15:     0x5573bbd064d5 - prometheus::histogram::HistogramCore::new::h44c50d33114f023d
                               at /home/steveej/.cargo/git/checkouts/rust-prometheus-0afd92d0f40cf12e/d919ccd/src/histogram.rs:176
  16:     0x5573bbd0773a - prometheus::histogram::Histogram::with_opts_and_label_values::h0e37452433a7a4d9
                               at /home/steveej/.cargo/git/checkouts/rust-prometheus-0afd92d0f40cf12e/d919ccd/src/histogram.rs:431
  17:     0x5573bbd076ad - prometheus::histogram::Histogram::with_opts::hf8eee9fddf910dd8
                               at /home/steveej/.cargo/git/checkouts/rust-prometheus-0afd92d0f40cf12e/d919ccd/src/histogram.rs:424
  18:     0x5573bbc33e88 - prometheus_histogram_value::main::he2c404422278eaec
                               at src/main.rs:5
  19:     0x5573bbc2ef30 - std::rt::lang_start::{{closure}}::h19e4aec872f6ee6d
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libstd/rt.rs:67
  20:     0x5573bbeb1483 - std::rt::lang_start_internal::{{closure}}::h0760fb8bd9f1a4c7
                               at src/libstd/rt.rs:52
  21:     0x5573bbeb1483 - std::panicking::try::do_call::hccaa7cebf2335ab2
                               at src/libstd/panicking.rs:292
  22:     0x5573bbeb333a - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:78
  23:     0x5573bbeb1e80 - std::panicking::try::h3ce8e2e4440720f0
                               at src/libstd/panicking.rs:270
  24:     0x5573bbeb1e80 - std::panic::catch_unwind::h2a767bac361346af
                               at src/libstd/panic.rs:394
  25:     0x5573bbeb1e80 - std::rt::lang_start_internal::h14e7168ba039f170
                               at src/libstd/rt.rs:51
  26:     0x5573bbc2ef09 - std::rt::lang_start::h59e9b7b8fac39f51
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libstd/rt.rs:67
  27:     0x5573bbc3429a - main
  28:     0x7f9835df7b8e - __libc_start_main
  29:     0x5573bbc2e16a - _start
  30:                0x0 - <unknown>
```

In addition to the crash, I also can't find a way how to set a value for the variable at runtime, although that's probably better to track in a separate issue.

/cc @lucab

**Comment by siddontang** [comment]
PTAL @breeswish

**Comment by mxinden** [comment]
@steveeJ https://github.com/tikv/rust-prometheus/issues/306 should fix the panic returning an error instead. In your example you are trying to create a `Histogram` with variable labels, as far as I know you would need to use a `HistogramVec` instead.
